### ISSUE TITLE
To Do

### ISSUE THREAD

**Issue by charliewilco** [charliewilco/dotfiles#2]
- [x] Move to NeoVim
- [x] Add current ZSH theme
- [x] Break Up vimrc & nvimrc
- [x] Find all recent Homebrew additions
- [x] Use Oceanic Next Colorscheme Everywhere
- [x] Use iTerm 2 Beta
- [x] get oceanic next for iterm in the svn call
- [x] configure symlinks for dotfiles
- [x] installer for zsh config

**Comment by charlespeters** [comment]
- [ ] get oceanic next for iterm in the svn call
- [ ] configure symlinks for dotfiles
- [ ] installer for zsh config

**Comment by charliewilco** [comment]
### Notes for Neovim install

The Neovim executable is called `nvim`. To use your existing Vim
configuration:
   `ln -s ~/.vim ~/.config/nvim`
   `ln -s ~/.vimrc ~/.config/nvim/init.vim`
See `:help nvim` for more information on Neovim.

**Comment by charliewilco** [comment]
init script
`bash -c "$(curl -LsS https://raw.github.com/charlespeters/dotfiles/master/scripts/init.sh)"`

curl https://raw.github.com/charlespeters/dotfiles/master/scripts/init.sh

**Comment by charliewilco** [comment]
bash <(curl -s https://raw.github.com/charlespeters/dotfiles/master/scripts/init.sh)
